---

- name: Use molecule to test all roles in the playbook.
  hosts: all
  become: yes
  become_user: root
  remote_user: root
  vars:
    update_apt_cache: yes
    force_ssh_authentication: no

  roles:
    - security
    - base
    - web
    - nginx
