---

vault_git_repo_ssh: git@github.com:YPCrumble/server-rendered-react-app.git
vault_git_repo_https: https://github.com/YPCrumble/server-rendered-react-app.git
vault_git_repo: "{{ vault_git_repo_ssh if nginx_use_letsencrypt==true else vault_git_repo_https }}"

# You can use the following Python script to adjust this value.
# pip install passlib
# python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"
vault_sudo_user_password: "$6$rounds=656000$BwutbncOD7MKMub/$hUJLBDj77Z9rhuypzpC2K/5oofWYjyLWCXiUc8qcJBi3exttAdnaA.f0TGzUMF0HhNqNFYNridBdD/egM.oX11"
