---

- include: install_additional_packages.yml
  tags: packages

- include: setup_known_hosts.yml

- include: create_users_and_groups.yml

- include: set_file_permissions.yml
  tags: deploy

- include: setup_environment.yml

- include: setup_application.yml
  become: no
  tags: deploy

- include: save_application.yml
  tags: deploy
