---

# SSH settings.
ssh_known_hosts_command: "ssh-keyscan -H -T 10"
ssh_known_hosts_file: "/etc/ssh/ssh_known_hosts"
ssh_known_hosts:
  - github.com


# Application settings.
environment_path: "/webapps/{{ application_name }}"
project_path: "{{ environment_path }}/{{ project_name }}"
application_log_dir: "{{ environment_path }}/logs"
application_log_file: "{{ application_log_dir }}/application.log"
application_cache_dir: "{{ environment_path }}/cache"
nodejs_port: 8081


# Nginx settings.
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
nginx_static_dir: "{{ project_path }}/static/"


# PM2 settings.
pm2_user: "{{ application_name }}"
pm2_group: webapps
